package com.example.auro.entity;

public enum Role {
    MANAGING_DIRECTOR,
    OPERATIONS_HEAD,

   SALES_MANAGER,
    MARKETING_MANAGER,
    CRM_MANAGER,
    ACCOUNTS_MANAGER,
    HR_MANAGER,

    SALES_EXECUTIVE,
    MARKETING_EXECUTIVE,
    CRM_EXECUTIVE,
    ACCOUNTS_EXECUTIVE,
    HR_EXECUTIVE,

    CUSTOMER
}
